config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
    }
  root 'surveys#index'
  resources :surveys
  devise_scope :user do
    #match "users/create_new_user" => "users/registrations#create_new_user", :controllers =>{:registrations => "users/registrations"}, :as => "create_new_account_user_registration",:via => :post
    #match "users/new_user" => "users/registrations#new_user", :controllers =>{:registrations => "users/registrations"},:as => "new_account_user_registration", :via => :get
    #match "users/:id" => "users/registrations#show", :controllers =>{:registrations => "users/registrations"},:as => "view_user_details", :via => :get
    get '/signout', to: 'devise/users#destroy', as: :signout
    #match "users/registration/index" => "users/registrations#index", :controllers =>{:registrations => "users/registrations"},:as => "index_users", :via => :get
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/survey.rb
class Survey < ApplicationRecord

  has_many :questions, inverse_of: :survey
  accepts_nested_attributes_for :questions, allow_destroy: true
  has_many :answer_data, inverse_of: :survey
  has_many :answers, inverse_of: :survey

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :authenticate_user!
    def new
      @survey = Survey.new

    end

    def create
      @survey = Survey.new(survey_params)
      if @survey.save
        @survey.questions.build
        #redirect_to surveys_path
        render plain: params[:survey].inspect
      else
        render action: :new
      end
    end

    def index
      @surveys = Survey.all
    end

    def edit
      @survey = Survey.find(params[:id])
    end

    def update
      @survey = Survey.find(params[:id])
      if @survey.update_attributes(survey_params)
        redirect_to @survey, notice: "Successfully updated survey."
      else
        render :edit
      end
    end

    def destroy
      @survey = Survey.find(params[:id])
      @survey.destroy
      redirect_to surveys_url, notice: "Successfully destroyed survey."
    end

    private

    def survey_params
      params.require(:survey).permit(:name, :description,
                                     questions_attributes: [:name,:survey_id ,:data_type,
                                                            answer_data_attributes: [:data_value,:question_id, :_destroy]])
    end

  end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_answer_datum_fields.html.erb
<fieldset>
  <%= f.label :data_value, "Answer" %>
  <%= f.text_field :data_value %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "remove", '#', class: "remove_fields" %>
</fieldset>

app/views/surveys/_form.html.erb
<%= form_for @survey do |f| %>
    <% if @survey.errors.any? %>
        <div class="error_messages">
          <h2><%= pluralize(@survey.errors.count, "error") %> prohibited this survey from being saved:</h2>
          <ul>
            <% @survey.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_field :description %>
    </div>
    <%= puts @survey.id %>
    <%= f.fields_for :questions do |builder| %>
        <%= render 'question_fields', f: builder %>
    <% end %>
    <%= link_to_add_fields "Add Question", f, :questions %>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/surveys/_question_fields.html.erb
<fieldset>
  <%= f.label :content, "Question" %><br />
  <%= f.text_area :name %><br />
  <%= link_to "remove", '#', class: "remove_fields" %>
  <%= f.label :data_type,"Select Type of Question" %>
  <%=  f.select :data_type, Question.data_types.keys, include_blank: true %>
  <%= f.fields_for :answer_data do |builder| %>
      <%= render 'answer_datum_fields', f: builder %>
  <% end %>
  <%= link_to_add_fields "Add Answer", f, :answer_data %>
</fieldset>

app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render "form" %>

app/views/surveys/index.html.erb
<h1>Surveys</h1>

<% @surveys.each do |survey| %>
    <div class="article">
      <h2><%= link_to survey.name, survey %></h2>
      <%= pluralize(survey.questions.size, "Question") %>
    </div>
<% end %>

<p><%= link_to 'New Survey', new_survey_path %></p>

app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render "form" %>

app/views/surveys/show.html.erb
<h1><%= @survey.name %></h1>

<ol class="questions">
  <% @survey.questions.each do |question| %>
      <li>
        <%= question.content %>
        <ol class="answers">
          <% question.answers.each do |answer| %>
              <li><%= answer.content %></li>
          <% end %>
        </ol>
      </li>
  <% end %>
</ol>

<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back to Surveys', surveys_path %>